[package]
name = "math"
version = "0.8.3"
authors = ["Aaron Zorel"]
edition = "2018"
license = "Apache-2.0"
description = "A math library"
repository = "https://github.com/Rustinante/math"

[dependencies]
log = "0.4.8"
num = "0.2"
rand = "0.7.0"
rayon = "1.1.0"
